config/routes.rb
Rails.application.routes.draw do
  get 'xiuxian/index'
  get 'questions/order',to: "questions#run_in_order"
  get 'questions/random',to: "questions#run_in_random"
  get 'questions/refresh_ids',to: "questions#refresh_ids"

  resources :questions



  devise_for :users
  get 'show2', to: "posts#show2"
  resources :posts do
    resources :comments

  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'feishu', to: 'common#feishu'
  get 'index', to: 'common#index'
  get 'index2', to: 'common#index2'
  get 'encode_upload', to: 'common#encode_upload'
  post 'encode_convert', to: 'common#encode_convert'

  match 'chatgpt', to: 'common#chatgpt', :via => [:get, :post]

  get 'persons/index'
  get 'search/index'

  post 'identity/image_verification', to: 'identity#image_verification'



  get 'deploy', to: 'tools#deploy'
  post 'tools/service_update', to: 'tools#service_update'
  get 'img_to_base64', to: 'tools#img_to_base64'
  post 'img_to_base64', to: 'tools#img_to_base64'

  get 'chat', to: 'chat_rooms#index'
  post 'chat/publish', to: 'chat_rooms#publish'
  get 'compress', to: 'tools#compress'
  get 'sense', to: 'tools#sense'
  post 'sense_encode', to: 'tools#sense_encode'
  get 'test_timeout', to: 'common#test_timeout'
  get 'test', to: 'common#test'
  get 'markdown', to: 'tools#markdown'
  get 'hammerspoon', to: 'tools#hammerspoon'
  get 'wow', to: 'tools#wow'
  get 'screen', to: 'tools#screen'
  get 'authorization', to: 'tools#authorization'
  post 'authorization', to: 'tools#authorization'

  get 'skills', to: 'common#skills'
  get 'items', to: 'common#items'
  get 'groups', to: 'common#groups'
  get 'rpc', to: 'tools#rpc'
  get 'rpc2', to: 'tools#rpc2'

  match 'fates/auth', to: 'fates#auth', :via => [:get, :post]

  resources :fates
  get 'yys', to: 'yys#index'

  get 'test', to: "yys#test"

  post 'yys/update_info', to: 'yys#update_info'
  get 'yys/guess', to: 'yys#guess'
  get 'yys/simulate', to: 'yys#simulate'
  match 'yys/auth', to: 'yys#auth', :via => [:get, :post]
  get 'yys/rate', to: 'yys#rate'
  post 'yys/summon', to: 'yys#summon'
  get 'yys/manage', to: 'yys#manage'
  post 'yys/update_manage', to: 'yys#update_manage'
  post 'yys/add_ss', to: 'yys#add_ss'
  post 'yys/add_patch', to: 'yys#add_patch'
  post 'yys/add_region', to: 'yys#add_region'

  match 'books/auth', to: 'books#auth', :via => [:get, :post]
  post 'books/category/:id', to: 'books#category'
  post 'books/prev/:start_pos/:id', to: 'books#prev'
  post 'books/next/:start_pos/:id', to: 'books#next'
  post 'books/goto', to: 'books#goto'
  post 'books/page_size', to: 'books#page_size'
  get 'books/es', to: 'books#es'
  get 'books/es_search', to: 'books#es_search'

  resources :books

  get 'colors', to: 'tools#colors'

  match 'json', to: 'tools#json', :via => [:get, :post]
  match 'sign', to: 'tools#sign', :via => [:get, :post]
  get 'unicode', to: 'tools#unicode'
  get 'json_format', to: 'tools#json_format'
  get 'mobile_area', to: 'tools#mobile_area'
  post 'get_mobile_area', to: 'tools#get_mobile_area'
  post 'comment_save', to: 'tools#comment_save'
  get '/v2/pause/manifests/3.1', to: 'tools#mirror'

  root 'common#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/fate.rb
class Fate < ApplicationRecord
end

app/controllers/fates_controller.rb
class FatesController < ApplicationController
  before_action :set_fate, only: [:show, :edit, :update, :destroy]

  before_action :require_auth, :except => [:auth]

  # GET /fates
  # GET /fates.json
  def index
    @fates = Fate.order(id: :desc).page(params[:page])
  end

  # GET /fates/1
  # GET /fates/1.json
  def show
  end

  # GET /fates/new
  def new
    @fate = Fate.new
  end

  # GET /fates/1/edit
  def edit
  end

  # POST /fates
  # POST /fates.json
  def create
    @fate = Fate.new(fate_params)

    if @fate.save
      redirect_to fates_path
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @fate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fates/1
  # PATCH/PUT /fates/1.json
  def update
    respond_to do |format|
      if @fate.update(fate_params)
        format.html { redirect_to @fate, notice: 'Fate was successfully updated.' }
        format.json { render :show, status: :ok, location: @fate }
      else
        format.html { render :edit }
        format.json { render json: @fate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fates/1
  # DELETE /fates/1.json
  def destroy
    @fate.destroy
    respond_to do |format|
      format.html { redirect_to fates_url, notice: 'Fate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def auth
    if request.post?
      if params[:password] == FATE_SECRET
        cookies[:fate_name] = {value: FATE_SECRET, expires: 30.days}
        redirect_to fates_path
      else
        flash[:alert] = 'wrong password.'
        redirect_to fates_auth_path
      end
    else
      cookies.delete :fate_name
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_fate
    @fate = Fate.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def fate_params
    params.fetch(:fate, {}).permit!
  end

  def require_auth
    if cookies[:fate_name] && cookies[:fate_name] == FATE_SECRET
      true
    else
      redirect_to fates_auth_path
    end
  end
end

app/helpers/fates_helper.rb
module FatesHelper
end

app/views/fates/_form.html.erb
<%= form_with(model: fate, local: true) do |form| %>
  <% if fate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fate.errors.count, "error") %> prohibited this fate from being saved:</h2>

      <ul>
        <% fate.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :title, style: 'width:1024px;height:40px;' %>

  <label for="fate_content"></label>
  <textarea id="fate_content" name="fate[content]">
  <%= @fate.content %>
</textarea>
  <div class="actions" style="text-align: right">
    <%= form.submit :commit, class: 'btn btn-info' %>
  </div>
<% end %>

app/views/fates/auth.html.erb
<style type="text/css">
  .text_tag {
    /*display: block;*/
    width: 50%;
    height: 54px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.42857143;
    color: #555;
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    border-radius: 4px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
    -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
    -o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
    transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
  }

</style>



<div style="padding-top: 200px;text-align: center;">
  <span style="color: red;"><%= flash[:alert] %></span>
  <%= form_tag(fates_auth_path, method: :post) do %>
    <%= password_field_tag :password, nil, :placeholder => 'please type the password', :class => 'text_tag', required: true %>
    <br>
    <br>
    <div style="text-align: center">
      <%= submit_tag :submit, :class => 'btn btn-primary' %>
    </div>

  <% end %>


</div>

app/views/fates/edit.html.erb
<h1>Editing Fate</h1>

<%= render 'form', fate: @fate %>

<%= link_to 'Show', @fate %> |
<%= link_to 'Back', fates_path %>

app/views/fates/index.html.erb
<p id="notice"><%= notice %></p>

<%= paginate @fates %>

<h1>&nbsp;</h1>

<table width="100%">
  <thead>
    <tr>
      <th>title</th>
      <th>content</th>
      <th colspan="3">operations</th>
    </tr>
  </thead>

  <tbody>
    <% @fates.each do |fate| %>
      <tr>
        <td><%= fate.title %></td>
        <td><%= fate.content[0,40] %></td>
        <td><%= link_to 'Show', fate %></td>
        <td><%= link_to 'Edit', edit_fate_path(fate) %></td>
        <td><%= link_to 'Destroy', fate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Fate', new_fate_path %>

app/views/fates/new.html.erb
<h1>New Fate</h1>

<%= render 'form', fate: @fate %>

<%= link_to 'Back', fates_path %>

app/views/fates/show.html.erb
<p id="notice"><%= notice %></p>

<%= @fate.title %>

<hr>
<%= raw @fate.content %>


<%= link_to 'Edit', edit_fate_path(@fate) %> |
<%= link_to 'Back', fates_path %>