config/routes.rb
Rails.application.routes.draw do
  get 'xiuxian/index'
  get 'questions/order',to: "questions#run_in_order"
  get 'questions/random',to: "questions#run_in_random"
  get 'questions/refresh_ids',to: "questions#refresh_ids"

  resources :questions



  devise_for :users
  get 'show2', to: "posts#show2"
  resources :posts do
    resources :comments

  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'feishu', to: 'common#feishu'
  get 'index', to: 'common#index'
  get 'index2', to: 'common#index2'
  get 'encode_upload', to: 'common#encode_upload'
  post 'encode_convert', to: 'common#encode_convert'

  match 'chatgpt', to: 'common#chatgpt', :via => [:get, :post]

  get 'persons/index'
  get 'search/index'

  post 'identity/image_verification', to: 'identity#image_verification'



  get 'deploy', to: 'tools#deploy'
  post 'tools/service_update', to: 'tools#service_update'
  get 'img_to_base64', to: 'tools#img_to_base64'
  post 'img_to_base64', to: 'tools#img_to_base64'

  get 'chat', to: 'chat_rooms#index'
  post 'chat/publish', to: 'chat_rooms#publish'
  get 'compress', to: 'tools#compress'
  get 'sense', to: 'tools#sense'
  post 'sense_encode', to: 'tools#sense_encode'
  get 'test_timeout', to: 'common#test_timeout'
  get 'test', to: 'common#test'
  get 'markdown', to: 'tools#markdown'
  get 'hammerspoon', to: 'tools#hammerspoon'
  get 'wow', to: 'tools#wow'
  get 'screen', to: 'tools#screen'
  get 'authorization', to: 'tools#authorization'
  post 'authorization', to: 'tools#authorization'

  get 'skills', to: 'common#skills'
  get 'items', to: 'common#items'
  get 'groups', to: 'common#groups'
  get 'rpc', to: 'tools#rpc'
  get 'rpc2', to: 'tools#rpc2'

  match 'fates/auth', to: 'fates#auth', :via => [:get, :post]

  resources :fates
  get 'yys', to: 'yys#index'

  get 'test', to: "yys#test"

  post 'yys/update_info', to: 'yys#update_info'
  get 'yys/guess', to: 'yys#guess'
  get 'yys/simulate', to: 'yys#simulate'
  match 'yys/auth', to: 'yys#auth', :via => [:get, :post]
  get 'yys/rate', to: 'yys#rate'
  post 'yys/summon', to: 'yys#summon'
  get 'yys/manage', to: 'yys#manage'
  post 'yys/update_manage', to: 'yys#update_manage'
  post 'yys/add_ss', to: 'yys#add_ss'
  post 'yys/add_patch', to: 'yys#add_patch'
  post 'yys/add_region', to: 'yys#add_region'

  match 'books/auth', to: 'books#auth', :via => [:get, :post]
  post 'books/category/:id', to: 'books#category'
  post 'books/prev/:start_pos/:id', to: 'books#prev'
  post 'books/next/:start_pos/:id', to: 'books#next'
  post 'books/goto', to: 'books#goto'
  post 'books/page_size', to: 'books#page_size'
  get 'books/es', to: 'books#es'
  get 'books/es_search', to: 'books#es_search'

  resources :books

  get 'colors', to: 'tools#colors'

  match 'json', to: 'tools#json', :via => [:get, :post]
  match 'sign', to: 'tools#sign', :via => [:get, :post]
  get 'unicode', to: 'tools#unicode'
  get 'json_format', to: 'tools#json_format'
  get 'mobile_area', to: 'tools#mobile_area'
  post 'get_mobile_area', to: 'tools#get_mobile_area'
  post 'comment_save', to: 'tools#comment_save'
  get '/v2/pause/manifests/3.1', to: 'tools#mirror'

  root 'common#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/yys_controller.rb
class YysController < ApplicationController
  before_action :require_auth, :except => [:auth, :all_cookies]

  def index
    config = HashWithIndifferentAccess.new(YAML.load(File.read(File.expand_path('../../../config/yys/yys.yml', __FILE__)))).deep_symbolize_keys
    @max_count = config[:max_pick_count] || 1000
  end

  def manage
    @summon = YysSummon.first
    @summon_modes = YysSummonMode.all
    ss1 = YysShiShen.sp.last(2)
    ss2 = YysShiShen.ssr.last(2)
    @shishens = ss1 + ss2
    @patch = YysPatch.last
  end

  def update_manage
    summon = YysSummon.first
    summon.mode_id = params[:mode_id]
    summon.sid = params[:sid]
    summon.up_count = params[:up_count]
    summon.save!
  end

  def add_ss
    ss = YysShiShen.new
    ss.sid = params[:sid]
    ss.name = params[:sname]
    ss.kind = params[:kind]
    ss.save!
  end

  def add_region
    ss = YysRegion.new
    ss.name = params[:name]
    ss.mode = params[:mode]
    ss.key = params[:key]
    ss.save!
  end

  def add_patch
    p = YysPatch.new
    p.version = params[:version]
    p.title = params[:title]
    p.content = params[:content]
    p.save!
  end

  def guess

  end

  def guess_info

  end

  def update_info

    red = []
    blue = []

    speed_arr = []

    attr = %i(damage  health armor speed crit_chance crit_damage hit resist)

    red_sids = params[:red].as_json.map { |k, v| v["sid"] }
    red_mids = params[:red].as_json.map { |k, v| v["mid"] }
    red_ahead_speed = ahead_attr('speed', red_sids)
    red_ahead_armor = ahead_attr('armor', red_sids)

    params[:red].as_json.deep_symbolize_keys.each do |k, v|
      speed_arr << v[:speed]
      v[:sname] = YysShiShen.find_by_sid(v[:sid]).try(:name)
      v[:mname] = YysMitama.find_by_mid(v[:mid]).try(:name)
      v[:kind] = 'red'
      v[:die] = false

      attr.each do |ar|
        v[ar] = v[ar].to_i
      end

      v[:damage_bound] = 0
      v[:speed_bound] = red_ahead_speed
      v[:armor_bound] = (v[:armor] * red_ahead_armor).to_i
      v[:max_health] = v[:health] * 2.4
      v[:curr_health] = v[:health] * 2.4
      v[:health_percent] = (v[:curr_health] * 1.0 / v[:max_health]).round(2)

      red << v
    end

    blue_sids = params[:blue].as_json.map { |k, v| v["sid"] }
    blue_mids = params[:blue].as_json.map { |k, v| v["mid"] }
    blue_ahead_speed = ahead_attr('speed', blue_sids)
    blue_ahead_armor = ahead_attr('armor', blue_sids)

    params[:blue].as_json.deep_symbolize_keys.each do |k, v|
      speed_arr << v[:speed]
      v[:sname] = YysShiShen.find_by_sid(v[:sid]).try(:name)
      v[:mname] = YysMitama.find_by_mid(v[:mid]).try(:name)
      v[:kind] = 'blue'
      v[:die] = false

      attr.each do |ar|
        v[ar] = v[ar].to_i
      end

      v[:damage_bound] = 0
      v[:speed_bound] = blue_ahead_speed
      v[:armor_bound] = (v[:armor] * blue_ahead_armor).to_i
      v[:max_health] = v[:health] * 2.4
      v[:curr_health] = v[:health] * 2.4
      v[:health_percent] = (v[:curr_health] * 1.0 / v[:max_health]).round(2)

      blue << v
    end

    YYS_REDIS.set('red', red.to_json)
    YYS_REDIS.set('blue', blue.to_json)
    YYS_REDIS.set('length', speed_arr.max.to_i)
    YYS_REDIS.set('red_resource', ahead_attr('resource', red_sids))
    YYS_REDIS.set('red_point', ahead_attr('point', red_sids, red_mids))
    YYS_REDIS.set('blue_resource', ahead_attr('resource', blue_sids))
    YYS_REDIS.set('blue_point', ahead_attr('point', red_sids, blue_mids))
  end

  def test

  end

  def simulate

    @red = JSON.parse(YYS_REDIS.get('red')).map { |x| x.deep_symbolize_keys }
    @blue = JSON.parse(YYS_REDIS.get('blue')).map { |x| x.deep_symbolize_keys }
    @result = {}

    all = @red + @blue

    max_len = YYS_REDIS.get('length').to_i

    all.each do |obj|
      _len = max_len - obj[:speed]
      _cost = _len * 1.00 / obj[:speed]
      obj[:cost] = _cost
      obj[:len] = obj[:speed]
    end

    100.times do |i|
      round_pick = all.sort_by { |v| v[:cost] }
      pick = round_pick.first
      pick_cost = pick[:cost]

      get_skill(pick)

      get_damage(pick)

      @result["round-#{i}"] = {}
      @result["round-#{i}"][:obj] = pick

      round_msg = []

      #if pick[1][:clear]
      #  blue.each do |kk,vv|
      #    if rand < 0.2
      #      clear_len = max_len*pick[1][:clear]
      #      vv[:len] = [vv[:len]-clear_len,0].max
      #      round_msg << "#{kk}被击退#{pick[1][:clear]*100}%行动条"
      #    end
      #  end
      #end

      # 下一个行动判定
      all.each do |v|
        actual_speed = v[:speed] + v[:speed_bound]
        if v[:sid] == pick[:sid]
          v[:len] = 0
        else
          fix_len = 0
          #if v[:spec] && v[:kind] != pick[1][:kind]
          #  fix_len = v[:spec] *max_len
          #  round_msg << "#{k}增加#{(v[:spec]*100).to_i}%行动条"
          #end
          v[:len] = [(pick_cost * actual_speed + fix_len + v[:len]), max_len].min
        end
        v[:cost] = (max_len - v[:len]) * 1.00 / actual_speed
      end
      @result["round-#{i}"][:msg] = round_msg
    end

  end

  def get_skill(obj)
    if obj[:kind] == 'blue'
      parties = JSON.parse(YYS_REDIS.get('blue')).map { |x| x.deep_symbolize_keys }.select { |x| x[:sid] != obj[:sid] }
      targets = JSON.parse(YYS_REDIS.get('red')).map { |x| x.deep_symbolize_keys }.select { |x| !x[:die] }
    else
      parties = JSON.parse(YYS_REDIS.get('red')).map { |x| x.deep_symbolize_keys }.select { |x| x[:sid] != obj[:sid] }
      targets = JSON.parse(YYS_REDIS.get('blue')).map { |x| x.deep_symbolize_keys }.select { |x| !x[:die] }
    end

    skill, target = YysAiSkill.new.ai_skill_200(1, parties, targets)

    obj[:round_skill] = skill
    obj[:round_target] = target

    obj[:round_begin_resource] = ''
    obj[:round_end_resource] = ''
    obj[:round_begin_point] = ''
    obj[:round_end_point] = ''

  end

  def ahead_attr(type, sids = [], mids = [])
    ahead_armor_sids = ['280'] # 先机防御：辉夜姬
    ahead_speed_sids = ['326', '330'] # 先机速度：sp驴、不知火

    armor_sids = sids & ahead_armor_sids
    speed_sids = sids & ahead_speed_sids

    # 鬼火
    init_resource = 4
    ahead_resource_sids = ['205'] # 先机鬼火：座敷童子
    ahead_resource_mitamas = ['107'] # 先机鬼火：火灵

    if (sids & ahead_resource_sids).present?
      init_resource += 3
    end

    if (mids & ahead_resource_mitamas).present?
      init_resource += 3
    end

    # 鬼火不能超过8
    init_resource = [init_resource, 8].min

    # 鬼火条
    init_point = 0
    ahead_point_sids = ['295'] # 先机鬼火条：追月神
    if (sids & ahead_point_sids).present?
      init_point += 4
    end

    case type
    when 'speed'
      return 0 if speed_sids.blank?
      speed_bound = 0
      if speed_sids.include? '326'
        speed_bound += 20
      end
      if speed_sids.include? '330'
        speed_bound += 20
      end
      return speed_bound
    when 'armor'
      return 0 if armor_sids.blank?
      if armor_sids.include? '280'
        return 0.2
      end
    when 'resource'
      return init_resource
    when 'point'
      return init_point
    else
      0
    end
  end

  # 计算其余五个目标受到的伤害
  def get_damage(obj)

    damage = {}
    if obj[:kind] == 'blue'
      targets = JSON.parse(YYS_REDIS.get('red')).select { |x| !x[:die] }
    else
      targets = JSON.parse(YYS_REDIS.get('blue')).select { |x| !x[:die] }
    end
    min_self_damage = obj[:damage] * (1 + obj[:damage_bound])
    max_self_damage = obj[:damage] * (1 + obj[:damage_bound]) * obj[:crit_damage] / 100

    # 技能加成
    skill_rate = 1

    # 裁判旗
    flag_rate = 1

    # 友方伤害加成
    damage_rate = 1

    # 浮动伤害
    float_rate = [1.01, 0.99].sample

    targets.each do |tt|
      tt = tt.deep_symbolize_keys
      damage[tt[:sid]] = {}
      target_rate = 1

      # todo 目标伤害加深

      # 目标血线导致的额外加成（御魂、技能等）
      mitama_rate = 1
      target_rate = target_rate * mitama_rate

      # 防御计算
      total_armor = tt[:armor] + tt[:armor_bound]
      armor_rate = total_armor * 1.00 / (total_armor + 300)
      target_rate = target_rate * armor_rate

      min_actual_damage = min_self_damage * skill_rate * flag_rate * damage_rate * float_rate * target_rate
      max_actual_damage = max_self_damage * skill_rate * flag_rate * damage_rate * float_rate * target_rate
      damage[tt[:sid]][:sname] = tt[:sname]
      damage[tt[:sid]][:curr_health] = tt[:curr_health]
      damage[tt[:sid]][:min_damage] = min_actual_damage.to_i
      if tt[:crit_chance] >= 100
        damage[tt[:sid]][:min_damage] = max_actual_damage.to_i
      end
      damage[tt[:sid]][:max_damage] = max_actual_damage.to_i
    end
    obj[:actual_damage] = damage
  end

  def summon
    number = params[:number].to_i
    number = 2000 if number > 2000
    all = params[:mode] ? true : false # 是否全图

    @show_cartoon = params[:cartoon] ? true : false # 是否展示抽卡动画

    summon = YysSummon.first
    summon_mode = summon.yys_summon_mode

    if summon_mode.code == 'SP'
      @result, @summon_count = summon_sp(number, all, summon.up_count)
    elsif summon_mode.code == 'SSR'
      @result, @summon_count = summon_ssr(number, all, summon.up_count)
    elsif summon_mode.code == 'SJ'
      @result, @summon_count = summon_sj(number, all, summon.up_count)
    else
      up_count = 0
      summon_common(number, up_count)
    end
  end

  def summon_common(number, up_count)
    ssrs = YysShiShen.ssr
    sps = YysShiShen.sp

    result = {}

    number.times do |num|
      seed1 = rand * 100
      if up_count > 0
        pick_rate = 1.25 * (1 + 2.5)
      else
        pick_rate = 1.25
      end
      if seed1 < pick_rate
        if up_count > 0
          up_count -= 1
        end

        if seed1 < (pick_rate / 1.25) # ssr
          ss = ssrs[rand ssrs.size]
        else
          # sp
          ss = sps[rand(sps.size)]
        end
        result[num + 1] = {}
        result[num + 1][:sid] = ss.sid
        result[num + 1][:name] = ss.name
        result[num + 1][:name_sp] = ss.name_sp
        result[num + 1][:cartoon] = ss.cartoon
        result[num + 1][:cartoon_sp] = ss.cartoon_sp

app/helpers/yys_helper.rb
module YysHelper

  def shishen_list
    YysShiShen.pluck(:name, :sid)
  end

  def mitama_list
    YysMitama.pluck(:name, :mid)
  end

  def position_list
    list = []
    5.times do |i|
      list << [i + 1, i + 1]
    end
    list
  end

  def rand_profile(type)
    case type
    when 'damage'
      1000 + rand(6000)
    when 'health'
      10000 + rand(25000)
    when 'armor'
      500 + rand(700)
    when 'speed'
      100 + rand(120)
    when 'crit_chance'
      5 + rand(110)
    when 'crit_damage'
      150 + rand(160)
    when 'hit'
      rand(90)
    when 'resist'
      20 + rand(80)
    else
      0
    end
  end

  def rand_shishen_resource(i)
    sid = []
    sid << 205 # 座敷童子
    sid << 266 # 青行灯
    sid << 280 # 辉夜姬
    sid << 295 # 追月神
    sid << 323 # 天井下
    sid << 298 # 薰

    sid[i]
  end

  def rand_sid
    YysShiShen.pluck(:sid).sample
  end

  def round_pick(n)

    ss = 221, 203, 187, 186, 165, 143, 135, 132, 128, 121

    _hash = {}
    ss.each_with_index do |s, i|
      _hash[s] = ss[0] * 1.00 / s
    end

    n.times do |i|

      min = _hash.values.min

      key = _hash.key min

      puts "round-#{i}: #{key}"

      fix_step = 0

      fix_step = 0.2 if key == 143

      _hash[key] += ss[0] * (1 - fix_step) * 1.00 / key
    end

  end

  def last_patch
    YysPatch.last
  end

  def patch_list
    YysPatch.order(id: :desc).pluck(:version, :content)
  end

  def region_drop_list
    YysRegion.order(:id).pluck(:name, :key)
  end

  def region_mode_drop_list
    YysRegion.all.pluck(:mode).uniq
  end

  def user_shi_shen_atlas
    spec_shi_shen_id = YysShiShen.spec.last.try(:id)

    list = []
    user_atlas = YysAtlas.find_by(nick_name: cookies[:yys_nick_name]).try(:sids) || []

    if user_atlas.count > 0
      YysShiShen.where(kind: 'origin').where.not(sid: spec_shi_shen_id).order(sid: :desc).each do |x|
        if user_atlas.include? x.sid
          x.owned = true
        else
          x.owned = false
        end
        list << x
      end
    else
      YysShiShen.where(kind: 'origin').where.not(sid: spec_shi_shen_id).order(sid: :desc).each do |x|
        x.owned = true
        list << x
      end
    end
  end

end

app/views/yys/_rate.html.erb
<hr>
<ul>
<!--  <li>召唤活动统计: <%#= image_tag image_path('tip.jpg'), size: "24", title: "统计条件:全图鉴,三次up,指定式神up,500抽(含)以上", style: 'vertical-align:top;' %>-->

<!--    <ul>-->
<!--      <li>活动抽取次数: <%#= rate[:all_count] %></li>-->
<!--      <li>500抽不出货: <%#= rate[:all_500_spec_count] %>人,概率:<%#= rate[:all_500_spec_rate] %>%</li>-->
<!--      <li>700抽才出货: <%#= rate[:all_700_spec_count] %>人,概率:<%#= rate[:all_700_spec_rate] %>%</li>-->
<!--    </ul>-->
<!--  </li>-->
  <li>召唤次数统计: <%= rate[:total_count] %></li>
</ul>

app/views/yys/_summon.html.erb
<hr>
<table class="stable">

  <% unless summon.each do |k, v| %>
    <tr>
      <td>
        第<%= k %>抽
      </td>
      <td style="text-indent: 10px;"><%= raw(v[:name]) %></td>
    </tr>
  <% end.present? %>
    <tr>
      <td colspan="2" style="color: red;"><%= '大人，非洲欢迎你。' %></td>
    </tr>
  <% end %>
</table>

<% if @msg.present? %>
  <hr>
  <% @msg.each do |k, v| %>

    <div style="font-size: 18px;color: #35a2ff;font-weight: bold;"><%= v %></div>
  <% end %>
<% end %>

app/views/yys/add_patch.js.erb
$("#patchModal").modal('hide')

app/views/yys/add_region.js.erb
$("#regionModal").modal('hide')

app/views/yys/manage.html.erb
<style type="text/css">
    table,th, tr, td {
        border: 1px solid grey;
        border-collapse: collapse;
        padding: 5px;
    }

    #patchModal input {
        min-width: 400px;
    }

    ul li {
        margin-bottom: 10px;
    }

</style>

<div style="width: 600px;margin: 0 auto;">
  <ul>
    <li>
      <button type="button" data-toggle="modal" data-target="#ssModal">添加式神</button>
    </li>
    <li>
      <button type="button" data-toggle="modal" data-target="#regionModal">添加大区</button>
    </li>
    <li>
      <button type="button" data-toggle="modal" data-target="#patchModal">添加patch</button>
    </li>
    <li>
      <table>
        <thead>
        <tr>
          <th>召唤模式</th>
          <th>up次数</th>
          <th>式神SID</th>
          <th>式神名称</th>
          <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td><%= @summon.yys_summon_mode.name %></td>
          <td><%= @summon.up_count %></td>
          <td><%= @summon.sid %></td>
          <td><%= @summon.yys_shi_shen.name %></td>
          <td>
            <button type="button" style="padding: 5px 5px;display: inline" data-toggle="modal" data-target="#manageModal">
              edit
            </button>
          </td>
        </tr>
        </tbody>
      </table>
    </li>
  </ul>
</div>



<div class="modal" id="regionModal" tabindex="-1" role="dialog" data-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">添加region</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag(yys_add_region_path, method: :post, remote: true) do %>
          <table width="100%">
            <tr>
              <td>mode:</td>
              <td><%= select_tag :mode, options_for_select(region_mode_drop_list) %><br></td>
            </tr>
            <tr>
              <td>name:</td>
              <td><%= text_field_tag :name %></td>
            </tr>
            <tr>
              <td>key:</td>
              <td><%= text_field_tag :key,nil,placeholder: 'zhuiyuezhutu' %></td>
            </tr>
          </table>

          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">submit</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        <% end %>
        </div>
  </div>
</div>

<div class="modal" id="patchModal" tabindex="-1" role="dialog" data-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">添加patch</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag(yys_add_patch_path, method: :post, remote: true) do %>
          <table width="100%">
            <tr>
              <td>version:</td>
              <td><%= text_field_tag :version, @patch.try(:version) %></td>
            </tr>
            <tr>
              <td>title:</td>
              <td><%= text_field_tag :title, @patch.try(:title) %></td>
            </tr>
            <tr>
              <td>content:</td>
              <td><%= text_field_tag :content, @patch.try(:content) %></td>
            </tr>
          </table>

          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">submit</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        <% end %>
        </div>
  </div>
</div>



<div class="modal" id="ssModal" tabindex="-1" role="dialog" data-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">添加式神</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag(yys_add_ss_path, method: :post, remote: true) do %>
          <table width="100%">
            <tr>
              <td>式神SID:</td>
              <td><%= number_field_tag :sid, 363 %></td>
            </tr>
            <tr>
              <td>式神名称:</td>
              <td><%= text_field_tag :sname %></td>
            </tr>
            <tr>
              <td>类型:</td>
              <td><%= select_tag "kind", options_for_select(%w[SSR SP], "SSR") %></td>
            </tr>
          </table>

          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">submit</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        <% end %>
        </div>
  </div>
</div>


<div class="modal" id="manageModal" tabindex="-1" role="dialog" data-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">召唤配置</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag(yys_update_manage_path, method: :post, remote: true) do %>
          <table width="100%">
            <tr>
              <td>召唤模式:</td>
              <td><%= select_tag "mode_id", options_from_collection_for_select(@summon_modes, "id", "name") %></td>
            </tr>
            <tr>
              <td>当期式神:</td>
              <td><%= select_tag "sid", options_from_collection_for_select(@shishens, "sid", "name") %></td>
            </tr>
            <tr>
              <td>up次数:</td>
              <td><%= number_field_tag :up_count, 3 %></td>
            </tr>
          </table>

          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">submit</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        <% end %>
        </div>
  </div>
</div>

app/views/yys/test.html.erb
<% (217..350).to_a.each do |i| %>
  skills << {sid: <%= i %>, skill_id: 1, skill_name: '', skill_kind: 'damage', skill_mode: 'unit', skill_damage: [1.2], extra: false} <br>
  skills << {sid: <%= i %>, skill_id: 2, skill_name: '', skill_kind: 'passive', extra: true}<br>
  skills << {sid: <%= i %>, skill_id: 3, skill_name: '', skill_kind: 'hybrid', skill_mode: 'group' ，skill_damage: [0.36, 0.36, 0.36], extra: false}
<br>
<br>

<% end %>

app/views/yys/update_info.js.erb
$("#update-info").html("阵容已更新！")

app/views/yys/update_manage.js.erb
$("#manageModal").modal('hide')