config/routes.rb
Rails.application.routes.draw do
  get 'xiuxian/index'
  get 'questions/order',to: "questions#run_in_order"
  get 'questions/random',to: "questions#run_in_random"
  get 'questions/refresh_ids',to: "questions#refresh_ids"

  resources :questions



  devise_for :users
  get 'show2', to: "posts#show2"
  resources :posts do
    resources :comments

  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'feishu', to: 'common#feishu'
  get 'index', to: 'common#index'
  get 'index2', to: 'common#index2'
  get 'encode_upload', to: 'common#encode_upload'
  post 'encode_convert', to: 'common#encode_convert'

  match 'chatgpt', to: 'common#chatgpt', :via => [:get, :post]

  get 'persons/index'
  get 'search/index'

  post 'identity/image_verification', to: 'identity#image_verification'



  get 'deploy', to: 'tools#deploy'
  post 'tools/service_update', to: 'tools#service_update'
  get 'img_to_base64', to: 'tools#img_to_base64'
  post 'img_to_base64', to: 'tools#img_to_base64'

  get 'chat', to: 'chat_rooms#index'
  post 'chat/publish', to: 'chat_rooms#publish'
  get 'compress', to: 'tools#compress'
  get 'sense', to: 'tools#sense'
  post 'sense_encode', to: 'tools#sense_encode'
  get 'test_timeout', to: 'common#test_timeout'
  get 'test', to: 'common#test'
  get 'markdown', to: 'tools#markdown'
  get 'hammerspoon', to: 'tools#hammerspoon'
  get 'wow', to: 'tools#wow'
  get 'screen', to: 'tools#screen'
  get 'authorization', to: 'tools#authorization'
  post 'authorization', to: 'tools#authorization'

  get 'skills', to: 'common#skills'
  get 'items', to: 'common#items'
  get 'groups', to: 'common#groups'
  get 'rpc', to: 'tools#rpc'
  get 'rpc2', to: 'tools#rpc2'

  match 'fates/auth', to: 'fates#auth', :via => [:get, :post]

  resources :fates
  get 'yys', to: 'yys#index'

  get 'test', to: "yys#test"

  post 'yys/update_info', to: 'yys#update_info'
  get 'yys/guess', to: 'yys#guess'
  get 'yys/simulate', to: 'yys#simulate'
  match 'yys/auth', to: 'yys#auth', :via => [:get, :post]
  get 'yys/rate', to: 'yys#rate'
  post 'yys/summon', to: 'yys#summon'
  get 'yys/manage', to: 'yys#manage'
  post 'yys/update_manage', to: 'yys#update_manage'
  post 'yys/add_ss', to: 'yys#add_ss'
  post 'yys/add_patch', to: 'yys#add_patch'
  post 'yys/add_region', to: 'yys#add_region'

  match 'books/auth', to: 'books#auth', :via => [:get, :post]
  post 'books/category/:id', to: 'books#category'
  post 'books/prev/:start_pos/:id', to: 'books#prev'
  post 'books/next/:start_pos/:id', to: 'books#next'
  post 'books/goto', to: 'books#goto'
  post 'books/page_size', to: 'books#page_size'
  get 'books/es', to: 'books#es'
  get 'books/es_search', to: 'books#es_search'

  resources :books

  get 'colors', to: 'tools#colors'

  match 'json', to: 'tools#json', :via => [:get, :post]
  match 'sign', to: 'tools#sign', :via => [:get, :post]
  get 'unicode', to: 'tools#unicode'
  get 'json_format', to: 'tools#json_format'
  get 'mobile_area', to: 'tools#mobile_area'
  post 'get_mobile_area', to: 'tools#get_mobile_area'
  post 'comment_save', to: 'tools#comment_save'
  get '/v2/pause/manifests/3.1', to: 'tools#mirror'

  root 'common#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/common_controller.rb
require 'net/http'
class CommonController < ApplicationController

  include XiuxianInfo

  skip_before_action :verify_authenticity_token, only: [:chatgpt]

  def sign_out

  end


  def feishu
    msg = {
      "msg_type": "post",
      "content": {
        "post": {
          "zh_cn": {
            "title": "告警通知",
             "content": [
            ]
          }
        }
      }
    }

    params["alerts"].each do |obj|
      para = []
      para << {"tag": "text", "text": "告警类型："+obj["labels"]["alertname"]+"\n"}
      para << {"tag": "text", "text": "告警对象："+obj["labels"]["node"]+"\n"}
      para << {"tag": "text", "text": "当前值："+obj["values"]["B"].to_s+"\n"}

      msg[:content][:post][:zh_cn][:content] << para
    end


    webhook_url = "https://open.feishu.cn/open-apis/bot/v2/hook/3eabd7fa-aa91-46f1-90e6-607d1a4c44b4"
    uri = URI.parse(webhook_url)
    header = {"Content-Type" => "application/json"}
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    request = Net::HTTP::Post.new(uri.path, header)
    request.body = msg.to_json

    response = http.request(request)
    puts response
    render text: "ok"
  end

  def chatgpt
    if request.post?
      api_key = "xxx"
      client = OpenAI::Client.new(
        access_token: api_key,
        log_errors: true # Highly recommended in development, so you can see what errors OpenAI is returning. Not recommended in production.
      )
      response = client.chat(
        parameters: {
          model: "gpt-3.5-turbo", # Required.
          messages: [{ role: "user", content: "Hello!"}], # Required.
          temperature: 0.7,
        })
      puts response.dig("choices", 0, "message", "content")
      # => "Hello! How may I assist you today?"
      puts response
    end
  end

  def test

    @c = %w(1607327664672)
  end

  def index
  end


  def colors

  end

  def encode_upload

  end

  def encode_convert
    file =  params[:file]
    file_name = file.original_filename
    content = file.read
    File.delete(file.tempfile.path) if File.exist?(file.tempfile.path)


    unless content.force_encoding('UTF-8').valid_encoding?
      content.encode!("utf-8", 'GB18030') rescue raise "unsupported encode, check the book"
    end


    send_data content, filename: file_name
  end



  def skills
    @skills = []
    100.times do
      @skills << rand_skill
    end
  end

  def items
    @items = []
    100.times do
      @items << rand_item
    end
  end

  def groups
    @groups = []
    100.times do
      @groups << rand_group
    end
  end


end

app/helpers/common_helper.rb
module CommonHelper
end

app/views/common/chatgpt.html.erb
<div style="background-color: #eae7e7;height: 600px;">
111
</div>
<div>
  message: <label>
  <textarea cols="80" rows="4"></textarea>
</label>
</div>

app/views/common/encode_upload.html.erb
<main id="site-main">
  <div style="padding-top: 200px;text-align: center;">
    <p style="color: red;font-size: 36px"><%= @notice %></p>
    <%= form_tag(encode_convert_path,multipart: true) do %>
      <%= token_tag %>
      <%= file_field_tag 'file' %>
      <br>
      <br>
      <div style="text-align: center">
        <%= submit_tag '提交', :class => 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</main>

app/views/common/groups.html.erb
<style type="text/css">
  td {
    border: 1px solid grey;
    padding: 15px 15px;
  }

  table {
    border-collapse: collapse;
  }
</style>

<table>
  <tr>
    <% @groups.each_with_index do |skill, i| %>
      <% if i % 12 == 0 %>
        </tr>
        <tr>
          <td><%= skill %></td>
      <% else %>
        <td><%= skill %></td>
      <% end %>
    <% end %>
    </table>

app/views/common/index.html.erb
<style>
        #container{
            background: black;
            width: 100%;
            height: 100%;
        }
      a {
          color: #ffffff;
      }

      #menu {
          position: absolute;
          bottom: 20px;
          width: 100%;
          text-align: center;
          font-family: verdana,Tahoma,Arial,Hei,"Microsoft Yahei",SimHei;
      }

      .element {
          width: 120px;
          height: 160px;
          box-shadow: 0px 0px 12px rgba(0,255,255,0.5);
          border: 1px solid rgba(127,255,255,0.25);
          text-align: center;
          cursor: default;
      }

      .element:hover {
          box-shadow: 0px 0px 12px rgba(0,255,255,0.75);
          border: 1px solid rgba(127,255,255,0.75);
      }

      .element .number {
          position: absolute;
          top: 20px;
          right: 20px;
          font-size: 12px;
          color: rgba(127,255,255,0.75);
      }

      .element .symbol {
          position: absolute;
          top: 40px;
          left: 0px;
          right: 0px;
          font-size: 60px;
          font-weight: bold;
          color: rgba(255,255,255,0.75);
          text-shadow: 0 0 10px rgba(0,255,255,0.95);
      }

      .element .details {
          position: absolute;
          bottom: 15px;
          left: 0px;
          right: 0px;
          font-size: 12px;
          color: rgba(127,255,255,0.75);
      }

      button {
          color: rgba(127,255,255,0.75);
          background: transparent;
          outline: 1px solid rgba(127,255,255,0.75);
          border: 0px;
          padding: 5px 10px;
          cursor: pointer;
      }
      button:hover {
          background-color: rgba(0,255,255,0.5);
      }
      button:active {
          color: #000000;
          background-color: rgba(0,255,255,0.75);
      }
  </style>

<%= javascript_include_tag '3D/three.min.js' %>
<%= javascript_include_tag '3D/tween.min.js' %>
<%= javascript_include_tag '3D/TrackballControls.js' %>
<%= javascript_include_tag '3D/CSS3DRenderer.js' %>

<div id="container"></div>

<script>

    var table = [
        "H", "Hydrogen", "1.00794", 1, 1,
        "He", "Helium", "4.002602", 18, 1,
        "Li", "Lithium", "#6.941", 1, 2,
        "Be", "Beryllium", "9.012182", 2, 2,
        "B", "Boron", "#10.811", 13, 2,
        "C", "Carbon", "#12.0107", 14, 2,
        "N", "Nitrogen", "#14.0067", 15, 2,
        "O", "Oxygen", "#15.9994", 16, 2,
        "F", "Fluorine", "18.9984032", 17, 2,
        "Ne", "Neon", "#20.1797", 18, 2,
        "Na", "Sodium", "22.98976...", 1, 3,
        "Mg", "Magnesium", "#24.305", 2, 3,
        "Al", "Aluminium", "26.9815386", 13, 3,
        "Si", "Silicon", "#28.0855", 14, 3,
        "P", "Phosphorus", "30.973762", 15, 3,
        "S", "Sulfur", "#32.065", 16, 3,
        "Cl", "Chlorine", "#35.453", 17, 3,
        "Ar", "Argon", "#39.948", 18, 3,
        "K", "Potassium", "#39.948", 1, 4,
        "Ca", "Calcium", "#40.078", 2, 4,
        "Sc", "Scandium", "44.955912", 3, 4,
        "Ti", "Titanium", "#47.867", 4, 4,
        "V", "Vanadium", "#50.9415", 5, 4,
        "Cr", "Chromium", "#51.9961", 6, 4,
        "Mn", "Manganese", "54.938045", 7, 4,
        "Fe", "Iron", "#55.845", 8, 4,
        "Co", "Cobalt", "58.933195", 9, 4,
        "Ni", "Nickel", "#58.6934", 10, 4,
        "Cu", "Copper", "#63.546", 11, 4,
        "Zn", "Zinc", "#65.38", 12, 4,
        "Ga", "Gallium", "#69.723", 13, 4,
        "Ge", "Germanium", "#72.63", 14, 4,
        "As", "Arsenic", "#74.9216", 15, 4,
        "Se", "Selenium", "#78.96", 16, 4,
        "Br", "Bromine", "#79.904", 17, 4,
        "Kr", "Krypton", "#83.798", 18, 4,
        "Rb", "Rubidium", "#85.4678", 1, 5,
        "Sr", "Strontium", "#87.62", 2, 5,
        "Y", "Yttrium", "88.90585", 3, 5,
        "Zr", "Zirconium", "#91.224", 4, 5,
        "Nb", "Niobium", "92.90628", 5, 5,
        "Mo", "Molybdenum", "#95.96", 6, 5,
        "Tc", "Technetium", "(98)", 7, 5,
        "Ru", "Ruthenium", "#101.07", 8, 5,
        "Rh", "Rhodium", "#102.9055", 9, 5,
        "Pd", "Palladium", "#106.42", 10, 5,
        "Ag", "Silver", "#107.8682", 11, 5,
        "Cd", "Cadmium", "#112.411", 12, 5,
        "In", "Indium", "#114.818", 13, 5,
        "Sn", "Tin", "#118.71", 14, 5,
        "Sb", "Antimony", "#121.76", 15, 5,
        "Te", "Tellurium", "127.6", 16, 5,
        "I", "Iodine", "126.90447", 17, 5,
        "Xe", "Xenon", "#131.293", 18, 5,
        "Cs", "Caesium", "#132.9054", 1, 6,
        "Ba", "Barium", "#132.9054", 2, 6,
        "La", "Lanthanum", "138.90547", 4, 9,
        "Ce", "Cerium", "#140.116", 5, 9,
        "Pr", "Praseodymium", "140.90765", 6, 9,
        "Nd", "Neodymium", "#144.242", 7, 9,
        "Pm", "Promethium", "(145)", 8, 9,
        "Sm", "Samarium", "#150.36", 9, 9,
        "Eu", "Europium", "#151.964", 10, 9,
        "Gd", "Gadolinium", "#157.25", 11, 9,
        "Tb", "Terbium", "158.92535", 12, 9,
        "Dy", "Dysprosium", "162.5", 13, 9,
        "Ho", "Holmium", "164.93032", 14, 9,
        "Er", "Erbium", "#167.259", 15, 9,
        "Tm", "Thulium", "168.93421", 16, 9,
        "Yb", "Ytterbium", "#173.054", 17, 9,
        "Lu", "Lutetium", "#174.9668", 18, 9,
        "Hf", "Hafnium", "#178.49", 4, 6,
        "Ta", "Tantalum", "180.94788", 5, 6,
        "W", "Tungsten", "#183.84", 6, 6,
        "Re", "Rhenium", "#186.207", 7, 6,
        "Os", "Osmium", "#190.23", 8, 6,
        "Ir", "Iridium", "#192.217", 9, 6,
        "Pt", "Platinum", "#195.084", 10, 6,
        "Au", "Gold", "196.966569", 11, 6,
        "Hg", "Mercury", "#200.59", 12, 6,
        "Tl", "Thallium", "#204.3833", 13, 6,
        "Pb", "Lead", "207.2", 14, 6,
        "Bi", "Bismuth", "#208.9804", 15, 6,
        "Po", "Polonium", "(209)", 16, 6,
        "At", "Astatine", "(210)", 17, 6,
        "Rn", "Radon", "(222)", 18, 6,
        "Fr", "Francium", "(223)", 1, 7,
        "Ra", "Radium", "(226)", 2, 7,
        "Ac", "Actinium", "(227)", 4, 10,
        "Th", "Thorium", "232.03806", 5, 10,
        "Pa", "Protactinium", "#231.0588", 6, 10,
        "U", "Uranium", "238.02891", 7, 10,
        "Np", "Neptunium", "(237)", 8, 10,
        "Pu", "Plutonium", "(244)", 9, 10,
        "Am", "Americium", "(243)", 10, 10,
        "Cm", "Curium", "(247)", 11, 10,
        "Bk", "Berkelium", "(247)", 12, 10,
        "Cf", "Californium", "(251)", 13, 10,
        "Es", "Einstenium", "(252)", 14, 10,
        "Fm", "Fermium", "(257)", 15, 10,
        "Md", "Mendelevium", "(258)", 16, 10,
        "No", "Nobelium", "(259)", 17, 10,
        "Lr", "Lawrencium", "(262)", 18, 10,
        "Rf", "Rutherfordium", "(267)", 4, 7,
        "Db", "Dubnium", "(268)", 5, 7,
        "Sg", "Seaborgium", "(271)", 6, 7,
        "Bh", "Bohrium", "(272)", 7, 7,
        "Hs", "Hassium", "(270)", 8, 7,
        "Mt", "Meitnerium", "(276)", 9, 7,
        "Ds", "Darmstadium", "(281)", 10, 7,
        "Rg", "Roentgenium", "(280)", 11, 7,
        "Cn", "Copernicium", "(285)", 12, 7,
        "Uut", "Unutrium", "(284)", 13, 7,
        "Fl", "Flerovium", "(289)", 14, 7,
        "Uup", "Ununpentium", "(288)", 15, 7,
        "Lv", "Livermorium", "(293)", 16, 7,
        "Uus", "Ununseptium", "(294)", 17, 7,
        "Uuo", "Ununoctium", "(294)", 18, 7
    ];

    var camera, scene, renderer;
    var controls;

    var objects = [];
    var targets = { table: [], sphere: [], helix: [], grid: [] };


    init();
    animate();

    function init() {

        camera = new THREE.PerspectiveCamera( 40, window.innerWidth / window.innerHeight, 1, 10000 );
        camera.position.z = 3000;

        scene = new THREE.Scene();

        // table

        for ( var i = 0; i < table.length; i += 5 ) {

            var element = document.createElement( 'div' );
            element.className = 'element';
            element.style.backgroundColor = 'rgba(0,127,127,' + ( Math.random() * 0.5 + 0.25 ) + ')';

            var number = document.createElement( 'div' );
            number.className = 'number';
            number.textContent = (i/5) + 1;
            element.appendChild( number );

            var symbol = document.createElement( 'div' );
            symbol.className = 'symbol';
            symbol.textContent = table[ i ];
            element.appendChild( symbol );

            var details = document.createElement( 'div' );
            details.className = 'details';
            details.innerHTML = table[ i + 1 ] + '<br>' + table[ i + 2 ];
            element.appendChild( details );

            var object = new THREE.CSS3DObject( element );
            object.position.x = Math.random() * 4000 - 2000;
            object.position.y = Math.random() * 4000 - 2000;
            object.position.z = Math.random() * 4000 - 2000;
            scene.add( object );

            objects.push( object );

            //

            var object = new THREE.Object3D();
            object.position.x = ( table[ i + 3 ] * 140 ) - 1330;
            object.position.y = - ( table[ i + 4 ] * 180 ) + 990;

            targets.table.push( object );

        }

        // sphere

        var vector = new THREE.Vector3();

        for ( var i = 0, l = objects.length; i < l; i ++ ) {

            var phi = Math.acos( -1 + ( 2 * i ) / l );
            var theta = Math.sqrt( l * Math.PI ) * phi;

            var object = new THREE.Object3D();

            object.position.x = 800 * Math.cos( theta ) * Math.sin( phi );
            object.position.y = 800 * Math.sin( theta ) * Math.sin( phi );
            object.position.z = 800 * Math.cos( phi );

            vector.copy( object.position ).multiplyScalar( 2 );

            object.lookAt( vector );

            targets.sphere.push( object );

        }

        // helix

        var vector = new THREE.Vector3();

        for ( var i = 0, l = objects.length; i < l; i ++ ) {

            var phi = i * 0.175 + Math.PI;

            var object = new THREE.Object3D();

            object.position.x = 900 * Math.sin( phi );
            object.position.y = - ( i * 8 ) + 450;
            object.position.z = 900 * Math.cos( phi );

            vector.x = object.position.x * 2;
            vector.y = object.position.y;
            vector.z = object.position.z * 2;

            object.lookAt( vector );

            targets.helix.push( object );

        }

        // grid

        for ( var i = 0; i < objects.length; i ++ ) {

            var object = new THREE.Object3D();

            object.position.x = ( ( i % 5 ) * 400 ) - 800;
            object.position.y = ( - ( Math.floor( i / 5 ) % 5 ) * 400 ) + 800;
            object.position.z = ( Math.floor( i / 25 ) ) * 1000 - 2000;

            targets.grid.push( object );

        }

        //

        renderer = new THREE.CSS3DRenderer();
        renderer.setSize( window.innerWidth, window.innerHeight );
        // renderer.domElement.style.position = 'absolute';
        document.getElementById( 'container' ).appendChild( renderer.domElement );

        //

        controls = new THREE.TrackballControls( camera, renderer.domElement );
        controls.rotateSpeed = 0.5;
        controls.minDistance = 500;
        controls.maxDistance = 6000;
        controls.addEventListener( 'change', render );


        setInterval(function () {
            animate()
            let elements = [targets.table, targets.sphere, targets.helix, targets.grid];
            let randomIndex = Math.floor(Math.random() * elements.length);
            let randomElement = elements[randomIndex];
            transform( randomElement, 2000 );
        },5000);

        transform( targets.table, 5000 );

        window.addEventListener( 'resize', onWindowResize, false );

    }

    function transform( targets, duration ) {

        TWEEN.removeAll();

        for ( var i = 0; i < objects.length; i ++ ) {

            var object = objects[ i ];
            var target = targets[ i ];

            new TWEEN.Tween( object.position )
                .to( { x: target.position.x, y: target.position.y, z: target.position.z }, Math.random() * duration + duration )
                .easing( TWEEN.Easing.Exponential.InOut )
                .start();

            new TWEEN.Tween( object.rotation )
                .to( { x: target.rotation.x, y: target.rotation.y, z: target.rotation.z }, Math.random() * duration + duration )
                .easing( TWEEN.Easing.Exponential.InOut )
                .start();

        }

        new TWEEN.Tween( this )
            .to( {}, duration * 2 )
            .onUpdate( render )
            .start();

    }

    function onWindowResize() {

        camera.aspect = window.innerWidth / window.innerHeight;
        camera.updateProjectionMatrix();

        renderer.setSize( window.innerWidth, window.innerHeight );

        render();

    }

    function animate() {

        requestAnimationFrame( animate );

        TWEEN.update();

        controls.update();

    }

    function render() {

        renderer.render( scene, camera );

    }

</script>

app/views/common/index2.html.erb
<div>
  <%= link_to '小说', books_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to '文本格式转换', encode_upload_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to '调色板', colors_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to 'wow', wow_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to 'sign', sign_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to '秘籍', skills_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <br>
  <%= link_to '法宝', items_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to '势力', groups_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to '号码归属地', mobile_area_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to '解压缩指令', compress_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to '图片转base64', img_to_base64_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to 'screen', screen_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <br>
  <%= link_to '聊天室', chat_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to 'hammerspoon', hammerspoon_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to '修仙', xiuxian_index_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to 'deploy', xiuxian_index_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
</div>
<hr>
<div>
  <%= link_to 'elasticsearch', books_es_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%#= link_to 'fate', su_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to 'json解析', json_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to 'unicode转码', unicode_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to 'yys', yys_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to 'sense', sense_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <br>
  <%= link_to 'markdown', markdown_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>
  <%= link_to 'authorization', authorization_path, class: 'nav-block', style: "background:" + RgbColor.fav_color, target: "_blank" %>

</div>

app/views/common/items.html.erb
<style type="text/css">
  td {
    border: 1px solid grey;
    padding: 15px 15px;
  }

  table {
    border-collapse: collapse;
  }
</style>

<table>
  <tr>
    <% @items.each_with_index do |skill, i| %>
      <% if i % 12 == 0 %>
        </tr>
        <tr>
          <td><%= skill %></td>
      <% else %>
        <td><%= skill %></td>
      <% end %>
    <% end %>
    </table>

app/views/common/sign_out.html.erb
You have sign out!

app/views/common/skills.html.erb
<style type="text/css">
  td {
    border: 1px solid grey;
    padding: 15px 15px;
  }

  table {
    border-collapse: collapse;
  }
</style>

<table>
  <tr>
    <% @skills.each_with_index do |skill, i| %>
      <% if i % 12 == 0 %>
        </tr>
        <tr>
          <td><%= skill %></td>
      <% else %>
        <td><%= skill %></td>
      <% end %>
    <% end %>
    </table>

app/views/common/test.html.erb
<style>
  td{
    border: 1px solid blue;
  }
  table{
      border-collapse: collapse;
  }
</style>
<table>
  <% @c.each do |x|  %>


    <tr>
      <% x.split(',') do |aa| %>
        <td><%= aa %></td>
    <% end %>
  </tr>

  <% end %>
</table>